"""Recompute Minian's ``YrA`` residual traces from the saved footprints and a replayed movie.

Why this exists
---------------
The ``YrA.zarr`` that Minian exported for every session was written by a second
pipeline run, roughly a year after the run that produced the ``A``/``C``/``S`` the
rest of ``caban`` depends on.  Its ``unit_id`` is sorted ascending while ``S``'s is
not, so row *i* of the exported ``YrA`` is generally a different cell from row *i*
of ``S``; in eight mice the two runs additionally disagree about a handful of
threshold-marginal cells.  ``sessions.Session._align_YrA_to_S_units`` repairs this
in memory at load time.  Recomputing ``YrA`` against the footprints that are
actually in ``A.zarr`` removes the need for the repair: ``compute_trace`` stamps
``A``'s ``unit_id`` straight onto its output, and ``A``'s ``unit_id`` equals
``S``'s elementwise.

See ``plans/yra_recompute_plan.md`` for the full argument, the evidence, and the
verification scheme this module implements.

What it does
------------
``YrA`` needs the motion-corrected movie ``Y``, which was never saved (except for
G10's conditioning session).  ``Y`` is therefore regenerated by replaying the
preprocessing chain recorded in ``pipeline-WORKING-TFC_cond-*.ipynb``::

    varr     = load_videos(...)                       # raw .avi frames, uint8
    varr     = drop del_frames                        # per-session, usually none
    varr_ref = varr - varr.min("frame")               # glow removal
    varr_ref = denoise(varr_ref, "median", ksize=5)
    varr_ref = remove_background(varr_ref, "tophat", wnd=15)
    Y        = apply_transform(varr_ref, motion, fill=0).astype(float)
    YrA      = compute_trace(Y, A, b, C, f)

``Y`` is never materialised to disk: at 608x608x~26k float64 it is ~77 GB per
session.  Every step above is a lazy dask operation and ``compute_trace``
consumes ``Y`` through ``tensordot``, so the chain streams from the ``.avi``
files.

Vendored Minian code
--------------------
The five operations above come from the Minian fork at
``~/code/minian_vsekulic`` (commit :data:`MINIAN_SOURCE_COMMIT`).  They
are vendored here rather than installed: Minian pins numpy 1.20 against this
environment's 2.4, so installing it would mean a second environment for five
functions, four of which are thin wrappers around cv2 and SimpleITK.  Each
vendored function carries a provenance comment naming its Minian source file, and
every deviation from the original is called out in that comment.
"""

import hashlib
import json
import os
import re
import subprocess
from datetime import datetime, timezone
from typing import List, Optional

import cv2
import dask
import dask.array as darr
import numpy as np
import pandas as pd
import SimpleITK as sitk
import sparse
import xarray as xr
from natsort import natsorted
from skimage.morphology import disk

from caban import session_queue as sq

# Provenance of the vendored code below.
MINIAN_SOURCE_REPO = "minian_vsekulic (origin/vsekulic_v4), at ~/code/minian_vsekulic"
MINIAN_SOURCE_COMMIT = "a3216ae2d9a1231146cdd9540f759f5fccbf7450"

# Preprocessing parameters, read out of the parameter cell of
# pipeline-WORKING-TFC_cond-1.ipynb (the notebook whose active `dpath` is G10's
# conditioning session).  The notebook overrides `ksize` and `wnd` further down
# with the same values it set here, so these are the values the pipeline ran with.
PARAM_LOAD_VIDEOS = {
    "pattern": r"[0-9]+\.avi$",
    "dtype": np.uint8,
    "downsample": dict(frame=1, height=1, width=1),
    "downsample_strategy": "subset",
}
PARAM_DENOISE = {"method": "median", "ksize": 5}
PARAM_BACKGROUND_REMOVAL = {"method": "tophat", "wnd": 15}

# Frames per dask chunk through the replay.  Purely a memory/throughput knob:
# every preprocessing step is per-frame and compute_trace reduces over
# (height, width), so the frame chunking cannot change the result.  At 250 a
# float64 chunk of the movie is ~0.74 GB.
DEFAULT_FRAME_CHUNK = 250

# Written next to the recomputed array; see `plans/yra_recompute_plan.md` 11.2.
OUTPUT_ARRAY_NAME = "YrA_recomputed.zarr"
SIDECAR_NAME = "YrA_recompute.json"

# Where the raw sessions live.  The output goes beside the A/C/S it was computed from
# (VS, 2026-09-26): YrA_recomputed.zarr and its sidecar inside that minian_crossreg*
# (or minian/) folder, next to the exported YrA.zarr, which is never touched.
DATA_ROOTS = sq.DATA_ROOTS_BACKUP

# A session is work for this module exactly when it has numbered .avi files and one
# minian_crossreg* folder holding all of these.  Globbing the folder rather than
# reading a path map is deliberate: G17's conditioning directory is deliberately
# misnamed on the server (plan 6.5) and must not be "fixed".
# Discovery constants live in caban.session_queue, shared with the CNMF-E pipeline.
MOUSE_DIR_PATTERN = sq.MOUSE_DIR_PATTERN
REQUIRED_MINIAN_ARRAYS = sq.REQUIRED_MINIAN_ARRAYS

# Per-session `del_frames`, harvested from every notebook in the Minian mirror
# (the RIKEN share mirror, now /Volumes/MINISCOPE/riken_share_mirror/vsekulic; all 60 *.ipynb including .ipynb_checkpoints and prev/).
#
# The scan found exactly one session anywhere in the corpus with a non-empty value,
# and it is not in this cohort: G25 is an SGFR1 mouse outside G05-G21 and its data is
# not on these drives.  Every other `del_frames` assignment in every notebook is the
# literal `del_frames = []`, and in the TFC_cond notebooks the deletion block is
# commented out entirely, guarded by a `dpath ==` test for that one G25 session.
#
# So the notebook-side answer for this cohort is "no frames dropped, anywhere".  That
# is recorded here as a default rather than retyped per session, and it stays a real
# cross-check: `derive_deleted_frames` recovers the truth from the saved `frame`
# coordinate independently, and a session where the two disagree is a hard failure
# (plan 6.1) that stops the run for a human to look at.
NOTEBOOK_DEL_FRAMES = {
    "G25-ST862-hM3D-SGFR1/2023_04_05-TFC_cond/16_00_27-TFC_cond": [
        4349, 4364, 6444, 6447, 6448, 9144, 9147, 9154, 9569, 9828, 10220, 10223,
        11719, 13537, 13915, 14081, 16368, 17018, 17038, 18219, 18632, 18639,
        18644, 18696, 18812, 18846, 25563,
    ],
}
NOTEBOOK_DEL_FRAMES_DEFAULT: List[int] = []


# Videos production never read, per session: recordings whose last files were never
# finalised, so their header carries no frame count (`ffprobe` nb_frames N/A) --
# Minian's load_avi_lazy needs it and cannot have read them. Established 2026-09-26
# (plan §15): production's C frame count equals exactly the sum over the remaining
# files, and the replay's own frame-count check re-proves that every run. Listed
# explicitly rather than skipped by rule, so an unreadable file anywhere else is
# still a hard failure.
UNUSED_VIDEOS = {
    # 19.avi: 865 decodable frames, no header count; at the end of the recording.
    "G15-ST721-hM4D/2022_01_13-TFC_test_B/16_19_13-TFC_test_B": ["19.avi"],
    # 11.avi: 593 decodable frames; 12.avi, 13.avi: 14 KB, no frames. In the MIDDLE of
    # the recording: production's C skips 3,000 timestamp rows after frame 10,999 (§15).
    "G21-ST762-hM4D/2022_03_24-TFC_test_B/14_35_02-TFC_test_B": ["11.avi", "12.avi", "13.avi"],
}


def _session_tail(session_dir: str) -> str:
    parts = os.path.normpath(session_dir).split(os.sep)
    if parts and parts[-1] == "Miniscope":
        parts = parts[:-1]
    return "/".join(parts[-3:])


def unused_videos(session_dir: str) -> List[str]:
    """The ``.avi`` files production did not read for this session (see :data:`UNUSED_VIDEOS`)."""
    return list(UNUSED_VIDEOS.get(_session_tail(session_dir), []))


def notebook_del_frames(session_dir: str) -> List[int]:
    """The ``del_frames`` the pipeline notebook recorded for this session.

    Matched on the ``<mouse>/<day>/<session>`` tail of the path so it works whichever
    root the data is read from.  See :data:`NOTEBOOK_DEL_FRAMES` for where the table
    comes from and why the default is empty.
    """
    return list(NOTEBOOK_DEL_FRAMES.get(_session_tail(session_dir), NOTEBOOK_DEL_FRAMES_DEFAULT))


# ---------------------------------------------------------------------------
# Vendored from Minian
# ---------------------------------------------------------------------------


def probe_video(fname: str) -> dict:
    """Return width, height and frame count of a video, via ``ffprobe``.

    Vendored behaviour of ``ffmpeg.probe`` as used by ``minian/utilities.py::
    load_avi_lazy``.  Deviation: the ``ffmpeg-python`` wrapper is not installed in
    this environment, so ``ffprobe`` is invoked directly.  The fields read are the
    same three the Minian code reads.
    """
    proc = subprocess.run(
        [
            "ffprobe", "-v", "error", "-select_streams", "v:0",
            "-show_entries", "stream=width,height,nb_frames",
            "-of", "json", fname,
        ],
        capture_output=True,
        check=True,
    )
    streams = json.loads(proc.stdout)["streams"]
    if len(streams) != 1:
        raise ValueError(
            "expected exactly one video stream in {}, found {}".format(fname, len(streams))
        )
    info = streams[0]
    return {
        "width": int(info["width"]),
        "height": int(info["height"]),
        "n_frames": int(info["nb_frames"]),
    }


def load_avi_ffmpeg(fname: str, h: int, w: int, f: int) -> np.ndarray:
    """Load an avi video using ``ffmpeg``.

    Vendored from ``minian/utilities.py::load_avi_ffmpeg``.  Deviation: the
    ``ffmpeg-python`` wrapper is replaced by the equivalent direct invocation --
    ``ffmpeg.input(fname).video.output("pipe:", format="rawvideo",
    pix_fmt="gray").run(capture_stdout=True)`` compiles to exactly this argument
    list.  The reshape and dtype are unchanged.
    """
    proc = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", fname, "-map", "0:v",
         "-f", "rawvideo", "-pix_fmt", "gray", "pipe:"],
        capture_output=True,
        check=True,
    )
    expected = f * h * w
    if len(proc.stdout) != expected:
        raise ValueError(
            "{}: ffmpeg returned {} bytes, expected {} for {} frames of {}x{}".format(
                fname, len(proc.stdout), expected, f, h, w
            )
        )
    return np.frombuffer(proc.stdout, np.uint8).reshape(f, h, w)


def load_avi_lazy(fname: str) -> darr.Array:
    """Lazily load an avi video as a single delayed task.

    Vendored from ``minian/utilities.py::load_avi_lazy``.  Deviation: dimensions
    come from :func:`probe_video` instead of ``ffmpeg.probe``.
    """
    info = probe_video(fname)
    return darr.from_delayed(
        dask.delayed(load_avi_ffmpeg)(
            fname, info["height"], info["width"], info["n_frames"]
        ),
        dtype=np.uint8,
        shape=(info["n_frames"], info["height"], info["width"]),
    )


def _video_list(vpath: str, pattern: str, exclude=()) -> List[str]:
    """The videos matching ``pattern``, natsorted, minus ``exclude`` (basenames).

    Every name in ``exclude`` must exist, so a stale exclusion is an error, not a no-op.
    """
    names = [v for v in os.listdir(vpath) if re.search(pattern, v)]
    missing = [e for e in exclude if e not in names]
    if missing:
        raise FileNotFoundError("videos to exclude not found in {}: {}".format(vpath, missing))
    vlist = natsorted([os.path.join(vpath, v) for v in names if v not in exclude])
    if not vlist:
        raise FileNotFoundError(
            "No data with pattern {} found in the specified folder {}".format(pattern, vpath)
        )
    return vlist


def load_videos(
    vpath: str,
    pattern=r"msCam[0-9]+\.avi$",
    dtype=np.float64,
    downsample=None,
    downsample_strategy="subset",
    exclude=(),
) -> xr.DataArray:
    """Load and concatenate the videos in a folder into an ``xr.DataArray``.

    Vendored from ``minian/utilities.py::load_videos``.  Deviations: the ``.tif``
    branch and the ``post_process`` hook are dropped (this pipeline uses neither,
    and an unsupported extension still raises), and the trailing
    ``custom_arr_optimize`` dask-graph rewrite is dropped -- it is a scheduler
    optimisation with no effect on values.  Addition: ``exclude`` drops named files
    (see :data:`UNUSED_VIDEOS`).
    """
    vpath = os.path.normpath(vpath)
    vlist = _video_list(vpath, pattern, exclude)
    print("loading {} videos in folder {}{}".format(
        len(vlist), vpath, " (excluding {})".format(list(exclude)) if exclude else ""))

    file_extension = os.path.splitext(vlist[0])[1]
    if file_extension not in (".avi", ".mkv"):
        raise ValueError("Extension not supported: {}".format(file_extension))

    varr_list = [load_avi_lazy(v) for v in vlist]
    varr = darr.concatenate(varr_list, axis=0)
    varr = xr.DataArray(
        varr,
        dims=["frame", "height", "width"],
        coords=dict(
            frame=np.arange(varr.shape[0]),
            height=np.arange(varr.shape[1]),
            width=np.arange(varr.shape[2]),
        ),
    )
    if dtype:
        varr = varr.astype(dtype)
    if downsample:
        if downsample_strategy == "mean":
            varr = varr.coarsen(**downsample, boundary="trim", coord_func="min").mean()
        elif downsample_strategy == "subset":
            varr = varr.isel(**{d: slice(None, None, w) for d, w in downsample.items()})
        else:
            raise NotImplementedError("unrecognized downsampling strategy")
    return varr.rename("fluorescence")


def denoise(varr: xr.DataArray, method: str, **kwargs) -> xr.DataArray:
    """Denoise the movie frame by frame.

    Vendored verbatim from ``minian/preprocessing.py::denoise``, restricted to the
    methods this pipeline uses.  The ``anisotropic`` branch is dropped because it
    needs ``medpy``, which is not installed; an unrecognised method still raises.
    """
    if method == "gaussian":
        func = cv2.GaussianBlur
    elif method == "median":
        func = cv2.medianBlur
    elif method == "bilateral":
        func = cv2.bilateralFilter
    else:
        raise NotImplementedError("denoise method {} not understood".format(method))
    res = xr.apply_ufunc(
        func,
        varr,
        input_core_dims=[["height", "width"]],
        output_core_dims=[["height", "width"]],
        vectorize=True,
        dask="parallelized",
        output_dtypes=[varr.dtype],
        kwargs=kwargs,
    )
    res = res.astype(varr.dtype)
    return res.rename(varr.name + "_denoised")


def remove_background_perframe(fm: np.ndarray, method: str, wnd: int, selem: np.ndarray) -> np.ndarray:
    """Remove background from a single frame.

    Vendored verbatim from ``minian/preprocessing.py::remove_background_perframe``.
    """
    if method == "uniform":
        raise NotImplementedError(
            "the uniform branch needs scipy.ndimage.uniform_filter and is not used by "
            "this pipeline; parameters recorded in the notebook are tophat/wnd=15"
        )
    elif method == "tophat":
        return cv2.morphologyEx(fm, cv2.MORPH_TOPHAT, selem)
    raise NotImplementedError("background removal method {} not understood".format(method))


def remove_background(varr: xr.DataArray, method: str, wnd: int) -> xr.DataArray:
    """Remove background from a video, frame by frame.

    Vendored verbatim from ``minian/preprocessing.py::remove_background``.
    """
    selem = disk(wnd)
    res = xr.apply_ufunc(
        remove_background_perframe,
        varr,
        input_core_dims=[["height", "width"]],
        output_core_dims=[["height", "width"]],
        vectorize=True,
        dask="parallelized",
        output_dtypes=[varr.dtype],
        kwargs=dict(method=method, wnd=wnd, selem=selem),
    )
    res = res.astype(varr.dtype)
    return res.rename(varr.name + "_subtracted")


def transform_perframe(fm: np.ndarray, tx_coef: np.ndarray, fill=0, param=None) -> np.ndarray:
    """Apply a rigid translation to a single frame, with linear subpixel interpolation.

    Vendored from ``minian/motion_correction.py::transform_perframe``, restricted
    to the rigid-translation branch (``motion.zarr`` has dims ``(frame,
    shift_dim)``, so the BSpline branch is unreachable here and its ``param``
    argument is kept only so the signature matches).  The interpolation is the one
    part of the replay with real substance -- integer shifting instead of
    ``sitkLinear`` would silently change ``Y``.
    """
    if np.ndim(tx_coef) > 1:
        raise NotImplementedError(
            "non-rigid (BSpline) motion is not used by this pipeline; motion.zarr "
            "carries per-frame (height, width) shifts"
        )
    tx = sitk.TranslationTransform(2, -tx_coef[::-1])
    fm = sitk.GetImageFromArray(fm)
    fm = sitk.Resample(fm, fm, tx, sitk.sitkLinear, fill)
    return sitk.GetArrayFromImage(fm)


def apply_transform(varr: xr.DataArray, trans: xr.DataArray, fill=0) -> xr.DataArray:
    """Apply the estimated motion to correct a movie.

    Vendored from ``minian/motion_correction.py::apply_transform``, restricted to
    the rigid branch (see :func:`transform_perframe`).
    """
    if "grid0" in trans.dims:
        raise NotImplementedError(
            "non-rigid (BSpline) motion is not used by this pipeline"
        )
    sh_dim = trans.coords["shift_dim"].values.tolist()
    varr_sh = xr.apply_ufunc(
        transform_perframe,
        varr.chunk({d: -1 for d in sh_dim}),
        trans,
        input_core_dims=[sh_dim, ["shift_dim"]],
        output_core_dims=[sh_dim],
        vectorize=True,
        dask="parallelized",
        kwargs={"fill": fill, "param": None},
        output_dtypes=[varr.dtype],
    )
    return varr_sh


def compute_trace(
    Y: xr.DataArray, A: xr.DataArray, b: xr.DataArray, C: xr.DataArray, f: xr.DataArray
) -> xr.DataArray:
    """Compute the residual traces ``YrA`` for each cell.

    Vendored from ``minian/cnmf.py::compute_trace``.  Deviation: the trailing
    ``custom_arr_optimize`` / ``da.optimize`` block is dropped -- it renames and
    inlines dask graph keys and has no effect on values.  The arithmetic, its
    order and its sparsity are unchanged.

    ``YrA_i = max(0, C_i + (<Ybs, A_i> - sum_j C_j <A_i, A_j>) / <A_i, A_i>)``.
    Note that the ``j == i`` term of the sum cancels ``C_i`` exactly, so ``YrA``
    depends on ``C`` only through the crosstalk of *overlapping* footprints.
    """
    fms = Y.coords["frame"]
    uid = A.coords["unit_id"]
    Y = Y.data
    A = darr.from_array(A.data.map_blocks(sparse.COO).compute(), chunks=-1)
    C = C.data.map_blocks(sparse.COO).T
    b = (
        b.fillna(0)
        .data.map_blocks(sparse.COO)
        .reshape((1, Y.shape[1], Y.shape[2]))
        .compute()
    )
    f = f.fillna(0).data.reshape((-1, 1))
    AtA = darr.tensordot(A, A, axes=[(1, 2), (1, 2)]).compute()
    A_norm = (
        (1 / (A ** 2).sum(axis=(1, 2)))
        .map_blocks(
            lambda a: sparse.diagonalize(sparse.COO(a)), chunks=(A.shape[0], A.shape[0])
        )
        .compute()
    )
    B = darr.tensordot(f, b, axes=[(1), (0)])
    Y = Y - B
    YtA = darr.tensordot(Y, A, axes=[(1, 2), (1, 2)])
    YtA = darr.dot(YtA, A_norm)
    CtA = darr.dot(C, AtA)
    CtA = darr.dot(CtA, A_norm)
    YrA = (YtA - CtA + C).clip(0)
    YrA = xr.DataArray(
        YrA,
        dims=["frame", "unit_id"],
        coords={"frame": fms, "unit_id": uid},
    )
    return YrA.transpose("unit_id", "frame")


# ---------------------------------------------------------------------------
# Session inputs
# ---------------------------------------------------------------------------


def open_minian_array(minian_dir: str, name: str) -> xr.DataArray:
    """Read one Minian ``<name>.zarr`` store as a dask-backed ``xr.DataArray``.

    ``zarr.load`` -- what ``sessions.py`` uses -- raises ``NotImplementedError`` on
    groups under zarr 3.x, and would give eager numpy anyway.  The replay needs
    the arrays lazy.
    """
    path = os.path.join(minian_dir, name + ".zarr")
    if not os.path.isdir(path):
        raise FileNotFoundError("no {} in {}".format(name + ".zarr", minian_dir))
    return xr.open_zarr(path, consolidated=False)[name]


def derive_deleted_frames(n_video_frames: int, frame_coord: np.ndarray) -> list:
    """Recover the per-session ``del_frames`` from a saved ``frame`` coordinate.

    The ``frame`` coordinate of ``C.zarr`` / ``motion.zarr`` is the post-deletion
    frame set, so the frames the notebook dropped are exactly those missing from
    it.  This is the independent derivation that :file:`plans/yra_recompute_plan.md`
    6.1 asks for: it is cross-checked against the notebook value rather than
    either being trusted alone.
    """
    frame_coord = np.asarray(frame_coord)
    if frame_coord.ndim != 1:
        raise ValueError("frame coordinate must be 1-D, got shape {}".format(frame_coord.shape))
    if len(np.unique(frame_coord)) != len(frame_coord):
        raise ValueError("frame coordinate has duplicate entries")
    if frame_coord.min() < 0 or frame_coord.max() >= n_video_frames:
        raise ValueError(
            "frame coordinate spans [{}, {}], outside the {} frames present in the "
            "videos -- the video folder and the Minian output do not belong together".format(
                frame_coord.min(), frame_coord.max(), n_video_frames
            )
        )
    return sorted(set(range(n_video_frames)) - set(frame_coord.tolist()))


def count_video_frames(video_dir: str, pattern: str, exclude=()) -> int:
    """Total frame count over the ``.avi`` files the replay will read."""
    return sum(probe_video(v)["n_frames"] for v in _video_list(video_dir, pattern, exclude))


def replay_motion_corrected_movie(
    video_dir: str,
    motion: xr.DataArray,
    del_frames: list,
    frame_chunk: int = DEFAULT_FRAME_CHUNK,
    exclude_videos=(),
) -> xr.DataArray:
    """Regenerate ``Y``: the motion-corrected, background-removed movie.

    Reproduces the preprocessing cells of ``pipeline-WORKING-TFC_cond-*.ipynb`` in
    order.  The result is lazy -- nothing but the per-pixel minimum used for glow
    removal is computed here.
    """
    varr = load_videos(video_dir, exclude=exclude_videos, **PARAM_LOAD_VIDEOS)
    if del_frames:
        varr = varr.where(~varr.frame.isin(del_frames), drop=True).astype("uint8")
    # The notebook's `subset = dict(frame=slice(0, None))` and `subset_mc = None`,
    # so `varr_ref = varr.sel(subset)` keeps every frame and every pixel.
    varr_ref = varr.chunk({"frame": frame_chunk, "height": -1, "width": -1})

    # Compare the frame values, not the coordinate DataArrays: the Minian arrays
    # carry scalar `animal`/`session` coords that ride along on `.frame` and make
    # `DataArray.equals` False for frame sets that are in fact identical.
    if not np.array_equal(varr_ref.frame.values, motion.frame.values):
        raise ValueError(
            "replayed movie has {} frames {}..{} but motion.zarr has {} frames {}..{}; "
            "del_frames is wrong or the video folder does not match the Minian output".format(
                varr_ref.sizes["frame"], int(varr_ref.frame[0]), int(varr_ref.frame[-1]),
                motion.sizes["frame"], int(motion.frame[0]), int(motion.frame[-1]),
            )
        )

    print("computing per-pixel minimum over {} frames for glow removal".format(varr_ref.sizes["frame"]))
    varr_min = varr_ref.min("frame").compute()
    varr_ref = varr_ref - varr_min
    varr_ref = denoise(varr_ref, **PARAM_DENOISE)
    varr_ref = remove_background(varr_ref, **PARAM_BACKGROUND_REMOVAL)
    Y = apply_transform(varr_ref, motion.chunk({"frame": frame_chunk}), fill=0)
    # The notebook saves `Y_fm_chk = Y.astype(float)` and feeds that to
    # compute_trace, so the cast happens before the trace, not inside it.
    return Y.astype(float).rename("Y")


# ---------------------------------------------------------------------------
# Provenance and idempotency
# ---------------------------------------------------------------------------


def hash_zarr_store(path: str) -> str:
    """SHA-256 over the on-disk bytes of a zarr store, in sorted path order."""
    digest = hashlib.sha256()
    for root, dirs, files in os.walk(path):
        dirs.sort()
        for name in sorted(files):
            fpath = os.path.join(root, name)
            digest.update(os.path.relpath(fpath, path).encode())
            with open(fpath, "rb") as fh:
                for block in iter(lambda: fh.read(1 << 20), b""):
                    digest.update(block)
    return digest.hexdigest()


def read_sidecar(output_dir: str) -> dict:
    return sq.read_sidecar(output_dir, SIDECAR_NAME)


def write_sidecar(output_dir: str, record: dict) -> str:
    return sq.write_sidecar(output_dir, SIDECAR_NAME, record)


HASHED_INPUTS = ("A", "C", "b", "f", "motion", "S")


def completed_run(output_dir: str, minian_dir: str, S_unit_id: np.ndarray):
    """Return the sidecar of a finished, still-valid run for this session, else ``None``.

    A session counts as done when the sidecar says so, the output is still on disk,
    every input still hashes to what the sidecar recorded, and the output's
    ``unit_id`` is still ``S``'s elementwise.  Anything less is not done: the
    reason is printed and the session is recomputed rather than quietly reused.
    """
    record = read_sidecar(output_dir)
    if not record:
        return None
    if not record.get("complete"):
        print("sidecar in {} marks an incomplete run; recomputing".format(output_dir))
        return None
    output_path = os.path.join(output_dir, OUTPUT_ARRAY_NAME)
    if not os.path.isdir(output_path):
        print("sidecar in {} has no {} beside it; recomputing".format(output_dir, OUTPUT_ARRAY_NAME))
        return None
    recorded = record.get("input_hashes", {})
    for name in HASHED_INPUTS:
        current = hash_zarr_store(os.path.join(minian_dir, name + ".zarr"))
        if recorded.get(name) != current:
            print("{}.zarr has changed since the recorded run; recomputing".format(name))
            return None
    written_ids = np.asarray(
        xr.open_zarr(output_path, consolidated=False)["YrA"].coords["unit_id"].values
    )
    if not np.array_equal(written_ids, np.asarray(S_unit_id)):
        print("{} unit_id no longer matches S; recomputing".format(OUTPUT_ARRAY_NAME))
        return None
    return record


# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------


def _per_cell_correlation(left: np.ndarray, right: np.ndarray) -> np.ndarray:
    """Pearson r between matching rows of two (unit, frame) matrices."""
    lc = left - left.mean(axis=1, keepdims=True)
    rc = right - right.mean(axis=1, keepdims=True)
    denom = np.linalg.norm(lc, axis=1) * np.linalg.norm(rc, axis=1)
    corr = np.full(left.shape[0], np.nan)
    good = denom > 0
    corr[good] = (lc[good] * rc[good]).sum(axis=1) / denom[good]
    return corr


def _summary(values: np.ndarray) -> dict:
    finite = values[np.isfinite(values)]
    if finite.size == 0:
        return {"n": 0, "n_undefined": int(values.size)}
    return {
        "n": int(finite.size),
        "n_undefined": int(values.size - finite.size),
        "median": float(np.median(finite)),
        "p5": float(np.percentile(finite, 5)),
        "p95": float(np.percentile(finite, 95)),
        "min": float(finite.min()),
    }


def footprint_overlap_ratio(A: xr.DataArray) -> np.ndarray:
    """Per unit, the mass of its footprint's overlap with *other* footprints.

    ``sum_{j != i} <A_i, A_j> / <A_i, A_i>``, the coefficient by which other units'
    traces enter ``YrA_i``.  In ``compute_trace`` the ``j == i`` term cancels
    ``C_i`` exactly, so this ratio is the whole of ``YrA_i``'s dependence on ``C``:
    a unit with ratio 0 has ``YrA_i = <Ybs, A_i> / <A_i, A_i>``, a function of the
    movie and its own footprint alone.

    That makes it the key to reading the comparison against the exported
    ``YrA.zarr``.  The export was computed from the ``C`` that existed *before* the
    second temporal update, and from that run's own footprints, while the ``C`` and
    ``A`` on disk are a different run's.  Disagreement that rises with this ratio
    is that known difference; disagreement at ratio 0 would mean the replay itself
    is wrong.
    """
    footprints = darr.from_array(A.data.map_blocks(sparse.COO).compute(), chunks=-1)
    AtA = darr.tensordot(footprints, footprints, axes=[(1, 2), (1, 2)]).compute()
    AtA = np.asarray(AtA.todense() if hasattr(AtA, "todense") else AtA)
    diagonal = np.diag(AtA).copy()
    off_diagonal = AtA.copy()
    np.fill_diagonal(off_diagonal, 0.0)
    return off_diagonal.sum(axis=1) / diagonal


def check_and_report(
    YrA_new: xr.DataArray,
    S_unit_id: np.ndarray,
    C: xr.DataArray,
    YrA_old: Optional[xr.DataArray],
    del_frames_derived: list,
    del_frames_notebook: list,
    overlap_ratio: np.ndarray,
) -> dict:
    """Run the hard assertions and build the review report of the plan's 11.6.

    Hard failures (this function raises): ``del_frames`` disagreement, a
    ``unit_id`` that is not ``S``'s elementwise, a shape or ``frame`` mismatch
    against ``C``, or any NaN/inf in the output.  Everything else is reported for
    the reader to judge.

    ``YrA_old`` is ``None`` for the 102 of 130 sessions that never had a ``YrA``
    exported -- the recall sessions of plan 11.7 step 4 and most of the LT
    sessions.  Those lean on the hard checks and on ``corr(C, YrA_new)``; the
    comparison block is then absent from the report rather than faked.
    """
    if list(del_frames_derived) != list(del_frames_notebook):
        raise ValueError(
            "del_frames disagree.\n"
            "  derived from the saved frame coordinate: {}\n"
            "  recorded in the pipeline notebook:       {}".format(
                del_frames_derived, del_frames_notebook
            )
        )

    new_ids = np.asarray(YrA_new.coords["unit_id"].values)
    S_unit_id = np.asarray(S_unit_id)
    if not np.array_equal(new_ids, S_unit_id):
        raise ValueError(
            "recomputed unit_id is not S's unit_id elementwise: {} of {} positions "
            "differ".format(int((new_ids != S_unit_id).sum()) if new_ids.shape == S_unit_id.shape
                            else "shape", len(S_unit_id))
        )
    if YrA_new.shape != C.shape:
        raise ValueError(
            "recomputed YrA has shape {} but C has shape {}".format(YrA_new.shape, C.shape)
        )
    if not np.array_equal(YrA_new.frame.values, C.frame.values):
        raise ValueError("recomputed YrA frame coordinate differs from C's")

    new = np.asarray(YrA_new.values)
    if not np.isfinite(new).all():
        n_nan = int(np.isnan(new).sum())
        n_inf = int(np.isinf(new).sum())
        raise ValueError(
            "recomputed YrA contains {} NaN and {} inf values".format(n_nan, n_inf)
        )

    C_values = np.asarray(C.values)
    floor_per_cell = (new == 0).mean(axis=1)
    report = {
        "del_frames": {
            "derived_from_frame_coord": list(del_frames_derived),
            "from_notebook": list(del_frames_notebook),
            "agree": True,
        },
        "n_units": int(len(new_ids)),
        "n_frames": int(YrA_new.sizes["frame"]),
        "corr_C_vs_new": _summary(_per_cell_correlation(new, C_values)),
        "clip_floor_fraction": {
            "overall": float((new == 0).mean()),
            "per_cell": _summary(floor_per_cell),
        },
        "vs_old_YrA": None,
    }
    if YrA_old is None:
        return report

    old_ids = np.asarray(YrA_old.coords["unit_id"].values)
    old_pos = {int(u): i for i, u in enumerate(old_ids)}
    shared = [int(u) for u in new_ids if int(u) in old_pos]
    new_rows = np.array([int(np.flatnonzero(new_ids == u)[0]) for u in shared], dtype=int)
    old_rows = np.array([old_pos[u] for u in shared], dtype=int)
    old = np.asarray(YrA_old.values)[old_rows]

    corr_vs_old = _per_cell_correlation(new[new_rows], old)
    abs_diff = np.abs(new[new_rows] - old)
    disagreeing = [
        {
            "unit_id": int(u),
            "corr": float(corr_vs_old[k]),
            "max_abs_diff": float(abs_diff[k].max()),
        }
        for k, u in enumerate(shared)
        if not (corr_vs_old[k] > 0.999)
    ]
    disagreeing.sort(key=lambda d: d["corr"])

    overlap_shared = np.asarray(overlap_ratio)[new_rows]
    by_overlap = []
    for low, high, label in (
        (-np.inf, 0.0, "none"),
        (0.0, 0.01, "0-1%"),
        (0.01, 0.10, "1-10%"),
        (0.10, np.inf, ">10%"),
    ):
        selected = (overlap_shared > low) & (overlap_shared <= high)
        if low == -np.inf:
            selected = overlap_shared <= 0
        if not selected.any():
            continue
        entry = {"overlap": label, "n_units": int(selected.sum())}
        entry.update(_summary(corr_vs_old[selected]))
        by_overlap.append(entry)

    report["vs_old_YrA"] = {
        "n_shared_units": len(shared),
        "unit_ids_new_only": sorted(set(new_ids.tolist()) - set(old_ids.tolist())),
        "unit_ids_old_only": sorted(set(old_ids.tolist()) - set(new_ids.tolist())),
        "corr": _summary(corr_vs_old),
        "max_abs_diff": float(abs_diff.max()),
        "n_units_below_r_0.999": len(disagreeing),
        "units_below_r_0.999": disagreeing[:50],
        "corr_by_footprint_overlap": by_overlap,
    }
    return report


def format_report(report: dict) -> str:
    """Render :func:`check_and_report`'s output for printing between sessions."""
    lines = []
    dl = report["del_frames"]
    lines.append("del_frames")
    lines.append("  derived from frame coord : {}".format(dl["derived_from_frame_coord"] or "[] (none dropped)"))
    lines.append("  from pipeline notebook   : {}".format(dl["from_notebook"] or "[] (none dropped)"))
    lines.append("")
    lines.append("recomputed YrA: {} units x {} frames".format(report["n_units"], report["n_frames"]))
    c = report["corr_C_vs_new"]
    lines.append("  corr(C, YrA_new) per cell : median {:.3f}  p5 {:.3f}  p95 {:.3f}".format(
        c["median"], c["p5"], c["p95"]))
    fl = report["clip_floor_fraction"]
    lines.append("  clip(0) floor             : {:.4f} of all samples; per cell median {:.4f}, p95 {:.4f}".format(
        fl["overall"], fl["per_cell"]["median"], fl["per_cell"]["p95"]))
    lines.append("")
    vo = report["vs_old_YrA"]
    if vo is None:
        lines.append("no YrA.zarr was ever exported for this session, so there is nothing to")
        lines.append("compare against; the hard checks above are what stand behind this one.")
        return "\n".join(lines)
    lines.append("against the existing YrA.zarr, matched by unit id")
    lines.append("  shared units              : {}".format(vo["n_shared_units"]))
    lines.append("  in new only               : {}".format(vo["unit_ids_new_only"] or "[]"))
    lines.append("  in old only               : {}".format(vo["unit_ids_old_only"] or "[]"))
    lines.append("  per-cell corr             : median {:.6f}  p5 {:.6f}  min {:.6f}".format(
        vo["corr"]["median"], vo["corr"]["p5"], vo["corr"]["min"]))
    lines.append("  max abs diff              : {:.6g}".format(vo["max_abs_diff"]))
    lines.append("  units with r <= 0.999     : {}".format(vo["n_units_below_r_0.999"]))
    lines.append("")
    lines.append("  per-cell corr split by footprint overlap -- the export used a different run's")
    lines.append("  C and footprints, and C reaches YrA_i only through overlapping units, so")
    lines.append("  agreement at zero overlap is what validates the replay:")
    for entry in vo["corr_by_footprint_overlap"]:
        lines.append("      overlap {:>5}  n = {:>4}  median r = {:.9f}  p5 {:.6f}  min {:.6f}".format(
            entry["overlap"], entry["n_units"], entry["median"], entry["p5"], entry["min"]))
    for entry in vo["units_below_r_0.999"]:
        lines.append("      unit {:>5}  r = {:.6f}  max|diff| = {:.6g}".format(
            entry["unit_id"], entry["corr"], entry["max_abs_diff"]))
    return "\n".join(lines)


def compare_replayed_movie(Y_new: xr.DataArray, saved_movie_path: str, n_frames: int = 50) -> dict:
    """Compare the replayed ``Y`` against a saved ``Y_fm_chk.zarr``, on a frame sample.

    This is step (1) of the plan's 7.1 gate, and it exists for exactly one session:
    G10's conditioning session is the only one whose ``minian_intermediate/`` was
    kept.  Comparing a sample rather than the whole movie keeps the check to one
    extra pass over a few hundred MB instead of 77 GB.
    """
    saved = xr.open_zarr(saved_movie_path, consolidated=False)["Y_fm_chk"]
    if not np.array_equal(Y_new.frame.values, saved.frame.values):
        raise ValueError("replayed Y and saved Y_fm_chk have different frame coordinates")
    idx = np.unique(np.linspace(0, Y_new.sizes["frame"] - 1, n_frames).astype(int))
    a = Y_new.isel(frame=idx).values
    b = saved.isel(frame=idx).values
    diff = np.abs(a - b)
    return {
        "n_frames_compared": int(len(idx)),
        "exactly_equal": bool(np.array_equal(a, b)),
        "max_abs_diff": float(diff.max()),
        "mean_abs_diff": float(diff.mean()),
        "n_pixels_differing": int((diff > 0).sum()),
    }


# ---------------------------------------------------------------------------
# The work queue
# ---------------------------------------------------------------------------
#
# Mechanism lives in `caban.session_queue`, shared with the local CNMF-E pipeline
# (`plans/local_minian_pipeline_plan.md` §9). What stays here is the policy: which
# sessions are *this* pipeline's work, and what its queue view reports.


def discover_sessions(
    roots=None,
    mouse_pattern: str = sq.MOUSE_DIR_PATTERN,
    minian_dir_overrides: Optional[dict] = None,
) -> List[sq.SessionWork]:
    """Find every session whose ``YrA`` can be recomputed.

    A session qualifies when it has numbered ``.avi`` files *and* a complete
    ``minian_crossreg*`` -- this pipeline recomputes a residual against footprints
    that already exist, so a session without them is not work here (it is work for
    the CNMF-E pipeline instead). Sessions with two complete Minian outputs raise
    unless pinned through ``minian_dir_overrides``; see
    :func:`caban.session_queue.resolve_minian_dir`.
    """
    candidates = sq.scan_sessions(roots=roots, mouse_pattern=mouse_pattern)
    items = []
    for candidate in candidates:
        if not candidate.n_avi or not candidate.complete_minian_dirs:
            continue
        minian_dir = sq.resolve_minian_dir(candidate, minian_dir_overrides)
        items.append(sq.SessionWork(
            candidate=candidate,
            minian_dir=minian_dir,
            output_dir=minian_dir,
        ))
    print("  -> {} of these are work for the YrA recompute".format(len(items)))
    return items


def output_present(item: sq.SessionWork) -> bool:
    """Cheap "looks finished" test for one item; see :func:`sq.output_present`."""
    return sq.output_present(item, SIDECAR_NAME, OUTPUT_ARRAY_NAME)


def next_pending(items: List[sq.SessionWork]) -> Optional[sq.SessionWork]:
    """The first session that is not already done, or ``None`` when all are.

    Position is re-derived from what is on disk on every call rather than held in a
    generator, so this survives a kernel restart and lands on the next session by
    itself once the current one finishes.
    """
    return sq.next_pending(items, SIDECAR_NAME, OUTPUT_ARRAY_NAME)


def _status_columns(item: sq.SessionWork, record: dict) -> dict:
    """The numbers that make this pipeline's queue readable at a glance.

    ``r_zero_overlap_median`` is the per-session gate: those units have ``YrA_i``
    determined by the replayed movie and their own footprint alone, so a value that
    is not ~0.999999 means that session's ``Y`` did not replay
    (`plans/yra_recompute_plan.md` §13.4).
    """
    report = record.get("report") or {}
    against_old = report.get("vs_old_YrA") or {}
    corr = against_old.get("corr") or {}
    by_overlap = against_old.get("corr_by_footprint_overlap") or []
    no_overlap = next((e for e in by_overlap if e["overlap"] == "none"), {})
    return {
        "has_old_YrA": item.existing_yra_path is not None,
        "has_saved_Y": item.saved_movie_path is not None,
        "n_units": report.get("n_units"),
        "n_frames": report.get("n_frames"),
        "r_vs_old_median": corr.get("median"),
        "r_zero_overlap_median": no_overlap.get("median"),
    }


def queue_status(items: List[sq.SessionWork]) -> pd.DataFrame:
    """One row per session: what it is, and whether it still needs doing."""
    frame = sq.queue_frame(items, SIDECAR_NAME, OUTPUT_ARRAY_NAME, _status_columns)
    order = ["mouse", "day", "session", "n_avi", "has_old_YrA", "has_saved_Y", "done",
             "n_units", "n_frames", "r_vs_old_median", "r_zero_overlap_median"]
    return frame[[c for c in order if c in frame.columns]]


def describe_item(item: sq.SessionWork) -> None:
    """Print what a work item is, before anything is computed."""
    print("{}".format(item.label))
    print("  videos      : {} .avi in {}".format(item.n_avi, item.session_dir))
    print("  minian      : {}".format(os.path.basename(item.minian_dir)))
    print("  old YrA     : {}".format(item.existing_yra_path or "none -- nothing to compare against"))
    print("  saved Y     : {}".format(item.saved_movie_path or "none"))
    print("  output      : {}".format(item.output_dir))
    print("  del_frames  : {} (from the notebook corpus)".format(
        notebook_del_frames(item.session_dir) or "[]"))
    print("  done        : {}".format(output_present(item)))


def preview_item(item: sq.SessionWork, **kwargs) -> dict:
    """Dry-run one work item: resolve and cross-check its inputs, compute nothing."""
    describe_item(item)
    print()
    return run_item(item, dry_run=True, **kwargs)


def run_item(
    item: sq.SessionWork,
    frame_chunk: int = DEFAULT_FRAME_CHUNK,
    dry_run: bool = False,
    force: bool = False,
) -> dict:
    """Recompute one work item, looking its ``del_frames`` up from the corpus table."""
    return recompute_session_yra(
        session_dir=item.session_dir,
        minian_dir=item.minian_dir,
        output_dir=item.output_dir,
        del_frames_notebook=notebook_del_frames(item.session_dir),
        existing_yra_path=item.existing_yra_path,
        saved_movie_path=item.saved_movie_path,
        frame_chunk=frame_chunk,
        dry_run=dry_run,
        force=force,
    )


def run_all(items: List[sq.SessionWork], stop_on_error: bool = True, **kwargs) -> List[dict]:
    """Work through the queue serially, printing each report before the next session."""
    return sq.run_queue(items, run_item, stop_on_error=stop_on_error, **kwargs)


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def recompute_session_yra(
    session_dir: str,
    minian_dir: str,
    output_dir: str,
    del_frames_notebook: list,
    existing_yra_path: Optional[str] = None,
    saved_movie_path: Optional[str] = None,
    frame_chunk: int = DEFAULT_FRAME_CHUNK,
    dry_run: bool = False,
    force: bool = False,
) -> dict:
    """Recompute one session's ``YrA`` and verify it.

    Parameters
    ----------
    session_dir
        The session's ``Miniscope`` folder, holding the numbered ``.avi`` files.
    minian_dir
        The folder holding ``A``/``C``/``b``/``f``/``motion`` ``.zarr`` for this
        session -- normally ``<session_dir>/minian_crossreg*``.
    output_dir
        Where ``YrA_recomputed.zarr`` and its sidecar are written.  The existing
        ``YrA.zarr`` is never touched.
    del_frames_notebook
        The frames the pipeline notebook dropped for this session.  Cross-checked
        against the value derived from the saved ``frame`` coordinate; a
        disagreement is a hard failure.
    existing_yra_path
        The exported ``YrA.zarr`` to compare against, or ``None`` for the sessions
        that never had one.
    saved_movie_path
        Optional ``minian_intermediate/Y_fm_chk.zarr``, present only for G10's
        conditioning session.  When given, the replayed ``Y`` is checked against it.
    dry_run
        Report the inputs and the derived ``del_frames``, then stop without
        computing or writing anything.
    force
        Recompute even when the sidecar says this session is already done.
    """
    A = open_minian_array(minian_dir, "A")
    C = open_minian_array(minian_dir, "C")
    b = open_minian_array(minian_dir, "b")
    f = open_minian_array(minian_dir, "f")
    motion = open_minian_array(minian_dir, "motion")
    # A NaN shift moves every pixel out of frame: the replayed Y would be all zeros and
    # so would YrA. Checked before `completed_run`, so an output already written from
    # such a motion is not accepted either. Found 2026-09-26 in two G05 TFC_test_B
    # production sessions whose saved motion.zarr is NaN in every frame.
    nan_frames = int(np.isnan(motion.values).any(axis=1).sum())
    if nan_frames:
        raise ValueError(
            "{}: motion.zarr is NaN in {} of {} frames, so Y cannot be replayed from it "
            "(it would be all zeros, and so would YrA). Production's movie was not: its "
            "C and max_proj are nonzero, so the saved motion is not the one that was "
            "applied.".format(minian_dir, nan_frames, motion.sizes["frame"]))
    S_unit_id = np.asarray(open_minian_array(minian_dir, "S").coords["unit_id"].values)

    A_unit_id = np.asarray(A.coords["unit_id"].values)
    if not np.array_equal(A_unit_id, S_unit_id):
        raise ValueError(
            "A.zarr and S.zarr disagree about unit_id in {}; the whole recompute rests "
            "on them being equal elementwise".format(minian_dir)
        )
    footprint_energy = (A ** 2).sum(["height", "width"]).compute().values
    if not (footprint_energy > 0).all():
        empty = A_unit_id[footprint_energy <= 0].tolist()
        raise ValueError(
            "units {} have all-zero footprints in A.zarr; compute_trace would divide "
            "by zero normalising them".format(empty)
        )

    if not force and not dry_run:
        done = completed_run(output_dir, minian_dir, S_unit_id)
        if done is not None:
            print("{} is already recomputed from these inputs ({}); nothing to do.".format(
                os.path.join(output_dir, OUTPUT_ARRAY_NAME), done["written_utc"]))
            print(format_report(done["report"]))
            return done

    excluded_videos = unused_videos(session_dir)
    n_video_frames = count_video_frames(session_dir, PARAM_LOAD_VIDEOS["pattern"], excluded_videos)
    del_frames_derived = derive_deleted_frames(n_video_frames, C.frame.values)

    print("session      : {}".format(session_dir))
    print("minian output: {}".format(minian_dir))
    print("units        : {}   frames in C: {}   frames in videos: {}".format(
        len(S_unit_id), C.sizes["frame"], n_video_frames))
    if excluded_videos:
        print("unused videos: {} (never read by production; UNUSED_VIDEOS)".format(excluded_videos))
    print("del_frames   : derived {}  |  notebook {}".format(
        del_frames_derived or "[]", list(del_frames_notebook) or "[]"))
    if dry_run:
        print("DRY_RUN: stopping before the replay.")
        return {"dry_run": True, "del_frames_derived": del_frames_derived,
                "del_frames_notebook": list(del_frames_notebook)}

    Y = replay_motion_corrected_movie(session_dir, motion, del_frames_derived, frame_chunk,
                                      exclude_videos=excluded_videos)

    movie_check = None
    if saved_movie_path:
        print("comparing the replayed Y against {}".format(saved_movie_path))
        movie_check = compare_replayed_movie(Y, saved_movie_path)
        print("  {}".format(movie_check))

    print("computing YrA over {} units x {} frames".format(len(S_unit_id), C.sizes["frame"]))
    YrA_new = compute_trace(
        Y, A, b, C.chunk({"unit_id": -1, "frame": frame_chunk}), f.chunk({"frame": frame_chunk})
    ).compute()

    YrA_old = None
    if existing_yra_path:
        YrA_old = xr.open_zarr(existing_yra_path, consolidated=False)["YrA"].compute()
    report = check_and_report(
        YrA_new, S_unit_id, C.compute(), YrA_old, del_frames_derived,
        list(del_frames_notebook), footprint_overlap_ratio(A),
    )
    if report["corr_C_vs_new"]["n"] == 0:
        raise ValueError(
            "{}: corr(C, YrA_new) is undefined for every unit -- the recomputed YrA is "
            "constant (all-zero clip floor {:.3f}); not writing it".format(
                minian_dir, report["clip_floor_fraction"]["overall"]))
    if movie_check is not None:
        report["replayed_Y_vs_saved_Y_fm_chk"] = movie_check

    output_path = os.path.join(output_dir, OUTPUT_ARRAY_NAME)
    if existing_yra_path and os.path.realpath(output_path) == os.path.realpath(existing_yra_path):
        raise ValueError(
            "refusing to write over the existing export at {}".format(existing_yra_path)
        )
    os.makedirs(output_dir, exist_ok=True)
    out = YrA_new.rename("YrA")
    for name in ("animal", "session"):
        if name in C.coords:
            out = out.assign_coords({name: C.coords[name]})
    out.to_dataset().to_zarr(output_path, mode="w", zarr_format=2, consolidated=False)
    print("wrote {}".format(output_path))

    record = {
        "written_utc": datetime.now(timezone.utc).isoformat(),
        "minian_source_repo": MINIAN_SOURCE_REPO,
        "minian_source_commit": MINIAN_SOURCE_COMMIT,
        "session_dir": session_dir,
        "minian_dir": minian_dir,
        "existing_yra_path": existing_yra_path,
        "saved_movie_path": saved_movie_path,
        "param_load_videos": {k: str(v) for k, v in PARAM_LOAD_VIDEOS.items()},
        "param_denoise": PARAM_DENOISE,
        "param_background_removal": PARAM_BACKGROUND_REMOVAL,
        "frame_chunk": frame_chunk,
        "del_frames": del_frames_derived,
        "unused_videos": excluded_videos,
        "n_video_frames": n_video_frames,
        "input_hashes": {
            name: hash_zarr_store(os.path.join(minian_dir, name + ".zarr"))
            for name in HASHED_INPUTS
        },
        "report": report,
        "complete": True,
    }
    write_sidecar(output_dir, record)
    print(format_report(report))
    return record
